import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tabas
 */
public class ContactDetail extends javax.swing.JFrame {

   
    public ContactDetail(Contact contact) {

    initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    this.setResizable(false);

    FnameField.setText(contact.getfName());
    LnameField.setText(contact.getlName());
    PhoneField.setText(contact.getPhone());
    Emailfield.setText(contact.getEmail());
    AddressField.setText(contact.getAddress());

    String fname = contact.getfName();
    String lname = contact.getlName();
    String fullName = fname + " " + lname;

    int id = contact.getId();
    ContactName.setText(fullName);

    
    String groupNames = getGroupsForContact(id);
    GroupField.setText(groupNames); 
    Deletebtn.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            
            new DeleteContact(id, groupNames).setVisible(true);
        }
    });
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        
        new EditContact(id, groupNames).setVisible(true);
    }
        
         
});

    }
    
    private String getGroupsForContact(int contactId) {
    StringBuilder groups = new StringBuilder();
    try {
        
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phonebook", "Ayesha", "password123");

        
        String query = "SELECT g.name FROM groupps g " +
                       "INNER JOIN contact_groups cg ON g.id = cg.group_id " +
                       "WHERE cg.contact_id = ?";
        PreparedStatement ps = conn.prepareStatement(query);
        ps.setInt(1, contactId);

        ResultSet rs = ps.executeQuery();

        
        while (rs.next()) {
            if (groups.length() > 0) {
                groups.append(", "); 
            }
            groups.append(rs.getString("name"));
        }

        
        rs.close();
        ps.close();
        conn.close();
    } catch (Exception ex) {
        JOptionPane.showConfirmDialog(null,"error occured" + ex);
    }

    return groups.length() > 0 ? groups.toString() : "No Group"; 
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ContactName = new javax.swing.JLabel();
        AddressField = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Emailfield = new javax.swing.JLabel();
        GroupField = new javax.swing.JLabel();
        PhoneField = new javax.swing.JLabel();
        LnameField = new javax.swing.JLabel();
        FnameField = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Editbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(59, 30, 84));

        ContactName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ContactName.setForeground(new java.awt.Color(255, 255, 255));
        ContactName.setText("ContactName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContactName)
                .addContainerGap(446, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ContactName)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        AddressField.setBackground(new java.awt.Color(155, 126, 189));
        AddressField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddressField.setText("Address");

        jLabel2.setBackground(new java.awt.Color(155, 126, 189));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(155, 126, 189));
        jLabel2.setText("Last Name");

        jLabel3.setBackground(new java.awt.Color(155, 126, 189));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(155, 126, 189));
        jLabel3.setText("Phone");

        jLabel4.setBackground(new java.awt.Color(155, 126, 189));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(155, 126, 189));
        jLabel4.setText("Group");

        jLabel5.setBackground(new java.awt.Color(155, 126, 189));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(155, 126, 189));
        jLabel5.setText("Email");

        jLabel6.setBackground(new java.awt.Color(155, 126, 189));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(155, 126, 189));
        jLabel6.setText("Address");

        jLabel7.setBackground(new java.awt.Color(155, 126, 189));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(155, 126, 189));
        jLabel7.setText("First Name");

        Emailfield.setBackground(new java.awt.Color(155, 126, 189));
        Emailfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Emailfield.setText("Email");

        GroupField.setBackground(new java.awt.Color(155, 126, 189));
        GroupField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GroupField.setText("Group");

        PhoneField.setBackground(new java.awt.Color(155, 126, 189));
        PhoneField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PhoneField.setText("Phone");

        LnameField.setBackground(new java.awt.Color(155, 126, 189));
        LnameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LnameField.setText("Last Name");

        FnameField.setBackground(new java.awt.Color(155, 126, 189));
        FnameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FnameField.setText("First Name");

        Backbtn.setBackground(new java.awt.Color(212, 190, 228));
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        Deletebtn.setBackground(new java.awt.Color(212, 190, 228));
        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });

        Editbtn.setBackground(new java.awt.Color(212, 190, 228));
        Editbtn.setText("Edit");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Backbtn)))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Editbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Deletebtn)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Emailfield)
                            .addComponent(GroupField)
                            .addComponent(PhoneField)
                            .addComponent(LnameField)
                            .addComponent(FnameField)
                            .addComponent(AddressField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FnameField)
                    .addComponent(jLabel7))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LnameField))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PhoneField))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GroupField))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Emailfield))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(AddressField))
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Deletebtn)
                            .addComponent(Editbtn)
                            .addComponent(Backbtn))
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        
            this.hide();// TODO add your handling code here:
        
    }//GEN-LAST:event_BackbtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
       
        
   
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditbtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressField;
    private javax.swing.JButton Backbtn;
    private javax.swing.JLabel ContactName;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Editbtn;
    private javax.swing.JLabel Emailfield;
    private javax.swing.JLabel FnameField;
    private javax.swing.JLabel GroupField;
    private javax.swing.JLabel LnameField;
    private javax.swing.JLabel PhoneField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
